#!/bin/bash
systemctl enable ly.service &&
systemctl enable NetworkManager.service &&
cd ~/.local/src/dwm &&
make clean install &&
cd ~/.local/src/dwmblocks &&
make clean install &&
cd ~/.local/src/dmenu &&
make clean install &&
cd ~/.local/src/st &&
make clean install &&
echo now you can reboot woot
