#!/bin/bash
cp -r $HOME/frogdots/.config ~/frogdots/.local $HOME &&
ln -sf $HOME/.config/shell/profile $HOME/.zprofile &&
ln -sf $HOME/.config/shell/profile $HOME/.bash_profile &&
ln -sf $HOME/.config/zsh/.zshrc $HOME/.zshrc &&
ln -sf $HOME/.config/shell/bashrc $HOME/.bashrc &&
ln -sf $HOME/.config/x11/xinitrc $HOME/.xinitrc &&
ln -sf $HOME/.config/x11/xprofile $HOME/.xprofile &&
ln -sf $HOME/.config/librewolf $HOME/librewolf
ln -sf $HOME/.local/share/img/bg/froggieesmol.png $HOME/.local/share/bg
paru -S --skipreview --noconfirm --needed - < packfull.txt
# ln -s ~/.config/x11/xresources ~/.xresources &&
