#!/bin/bash
# systemctl enable ly.service &&
systemctl enable NetworkManager.service &&
pacman -Rsu $(comm -23 <(pacman -Qq | sort) <(sort packfull.txt))
echo "now you can reboot and build your desktop in '$HOME/.local/src' woot"
